fix: bugs fix
Test-Account666/OpenShulker pull request #2
Opened 2024-10-09 08:50 UTC by Sh1roCu

fix hopper conflict;
fix reload-command cant's reload config correctly.

2024-10-09 11:37 UTC, Test-Account666 requested changes
Thanks for the Pull Request btw :)

2024-10-09 11:37 UTC, Test-Account666 commented on src/main/java/me/entity303/openshulker/commands/OpenShulkerCommand.java
> +            this._openShulker.reloadCfg();
I don't see a point in creating the reloadCfg method.

Just publicize `InitializeConfig` and execute that.

2024-10-09 20:17 UTC, Sh1roCu reviewed
done

2024-10-16 10:25 UTC, Test-Account666 approved these changes
Looks fine to me now. Thanks for your contribution. I really appreciate it :)

2024-10-16 10:25 UTC, merged